### ISSUE TITLE
Laravel 5.4 fresh install issues with LangFileManager?

### ISSUE THREAD

**Issue by pushamaku** [Laravel-Backpack/PermissionManager#54]
Had some issues upgrading so decided to do a fresh local 5.4 install, and slowly integrate all my changes.

I followed your guide as on:

[Install on Laravel 5.4](https://laravel-backpack.readme.io/v3.0/docs/install-on-laravel-54)

From the Optionals, I installed: 

LangFileManager 
BackupManager 
Settings
PermissionManager 

Loaded up the app in the browser and so far so good, until I decide to try admin/user, I got datatables error:

![image](https://cloud.githubusercontent.com/assets/19703660/22912358/65432cd4-f2a8-11e6-8a09-692592179c2c.png)

errors from user/search xhr call:

```
1/3
BadMethodCallException in Builder.php line 2508:
Call to undefined method Illuminate\Database\Query\Builder::translationEnabled()

2/3
ErrorException in Builder.php line 2508:
Call to undefined method Illuminate\Database\Query\Builder::translationEnabled() (View: C:\xampp\htdocs\admin\resources\views\vendor\backpack\crud\buttons\update.blade.php)

3/3
ErrorException in Builder.php line 2508:
Call to undefined method Illuminate\Database\Query\Builder::translationEnabled() (View: C:\xampp\htdocs\admin\resources\views\vendor\backpack\crud\buttons\update.blade.php) (View: C:\xampp\htdocs\admin\resources\views\vendor\backpack\crud\buttons\update.blade.php)

```

Thank you

**Comment by pushamaku** [comment]
Resolved issue. I forgot to update my User model:

```
use Backpack\CRUD\CrudTrait; // PermissionManager
use Spatie\Permission\Traits\HasRoles; // PermissionManager
```

```
use CrudTrait; // PermissionManager
use HasRoles; // PermissionManager
```

Thanks!

**Comment by shinokada** [comment]
Mmmm, I had the same problem. I have all code as above, I still get the same errors.
